Fysio/Areas/Patient/Controllers/PatientFileController.cs
using Domain;
using DomainServices.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Fysio.Areas.Patient.Controllers
{
    [Area("Patient")]
    [Authorize(Policy = "RequirePatient")]
    public class PatientFileController : Controller
    {
        private readonly IPatientRepository patientRepository;
        private readonly IPatientFileRepository patientFileRepository;
        private readonly ITreatmentRepository treatmentRepository;
        private readonly UserManager<IdentityUser> userManager;

        public PatientFileController(IPatientRepository patientRepository, IPatientFileRepository patientFileRepository, ITreatmentRepository treatmentRepository, UserManager<IdentityUser> userManager)
        {
            this.patientRepository = patientRepository;
            this.patientFileRepository = patientFileRepository;
            this.userManager = userManager;
            this.treatmentRepository = treatmentRepository;
        }

        public IActionResult Index()
        {
            IdentityUser usr = userManager.GetUserAsync(HttpContext.User).Result;
            string email = usr.Email;
            Domain.Patient p = patientRepository.GetPatientByEmail(email);

            PatientFile pf = patientFileRepository.GetCurrentPatientFileForPatient(p);
            if(pf != null)
            {
                return View(pf);
            } else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        public IActionResult TreatmentDetail(int id)
        {
            Treatment t = treatmentRepository.GetTreatmentById(id);
            return View(t);
        }
    }
}

Fysio/Areas/Treator/Controllers/PatientFileController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Domain;
using DomainServices.Interfaces;
using DomainServices.Services;
using Fysio.Areas.Treator.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace Fysio.Areas.Treator.Controllers
{
    [Area("Treator")]
    [Authorize(Policy = "RequireTreator")]
    public class PatientFileController : Controller
    {
        private readonly IPatientFileRepository patientFileRepository;
        private readonly IPatientRepository patientRepository;
        private readonly ITreatorRepository treatorRepository;
        private readonly ICommentRepository commentRepository;
        private readonly AddAppointmentService addAppointmentService;

        public PatientFileController(IPatientFileRepository repository, IPatientRepository patientRepository, ITreatorRepository treatorRepository, ICommentRepository commentRepository, AddAppointmentService addAppointmentService)
        {
            patientFileRepository = repository;
            this.patientRepository = patientRepository;
            this.treatorRepository = treatorRepository;
            this.commentRepository = commentRepository;
            this.addAppointmentService = addAppointmentService;
        }

        public IActionResult Index(int id, PatientFile patientFile)
        {
            if(patientFile != null)
            {
                if(patientFile.StartDate != DateTime.MinValue && patientFile.Patient != null)
                {
                    return View(patientFile);
                } else
                {
                    if (patientFile.Age != 0)
                    {
                        PatientFile pf = patientFileRepository.GetPatientFileById(patientFile.Id);
                        return View(pf);
                    } else
                    {
                        PatientFile pf = patientFileRepository.GetCurrentPatientFileForPatient(patientRepository.GetPatientById(id));
                        return View(pf);
                    }
                }
            } else
            {
                return View(patientFile);
            }
        }

        [HttpGet]
        public IActionResult AddComment(int id)
        {
            return View(new CommentModel() { PatientFileId = id});
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddComment(CommentModel model)
        {
            if (ModelState.IsValid)
            {
                ClaimsPrincipal currentUser = this.User;
                string email = currentUser.FindFirst(ClaimTypes.Email).Value;
                Domain.Treator creator = treatorRepository.GetTreatorByEmail(email);

                Comment c = new Comment(model.Description, DateTime.Now, creator, model.VisibleForPatient);
                commentRepository.AddComment(c);

                PatientFile pf = patientFileRepository.GetPatientFileById(model.PatientFileId);
                pf.Comments.Add(c);
                patientFileRepository.UpdatePatientFile(pf);

                return RedirectToAction("Index", "PatientFile", pf);
            } else
            {
                return View(new CommentModel() { PatientFileId = model.PatientFileId });
            }
        }
    }
}

Fysio/Areas/Treator/Controllers/TreatmentController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Fysio.Areas.Treator.Models;
using Domain;
using DomainServices.Interfaces;
using System.Security.Claims;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;
using DomainServices.Services;

namespace Fysio.Areas.Treator.Controllers
{
    [Area("Treator")]
    [Authorize(Policy = "RequireTreator")]
    public class TreatmentController : Controller
    {
        private readonly ITreatmentRepository treatmentRepository;
        private readonly ITreatorRepository treatorRepository;
        private readonly IPatientRepository patientRepository;
        private readonly IPatientFileRepository patientFileRepository;
        private readonly ITreatmentTypeRepository treatmentTypeRepository;
        private readonly UserManager<IdentityUser> userManager;
        private readonly AddTreatmentService addTreatmentService;

        public TreatmentController(ITreatmentRepository treatmentRepository, ITreatorRepository treatorRepository, IPatientRepository patientRepository, IPatientFileRepository patientFileRepository, UserManager<IdentityUser> userManager, ITreatmentTypeRepository treatmentTypeRepository, AddTreatmentService addTreatmentService)
        {
            this.treatmentRepository = treatmentRepository;
            this.treatorRepository = treatorRepository;
            this.patientRepository = patientRepository;
            this.patientFileRepository = patientFileRepository;
            this.treatmentTypeRepository = treatmentTypeRepository;
            this.userManager = userManager;
            this.addTreatmentService = addTreatmentService;
        }

        public IActionResult Index(int id)
        {
            Treatment t = treatmentRepository.GetTreatmentById(id);
            return View(t);
        }
        
        [HttpGet]
        public IActionResult AddTreatment(string p, int id)
        {
            Treatment t = treatmentRepository.GetTreatmentById(id);
            ViewBag.TreatmentTypes = GetTreatmentTypes();
            if(t != null)
            {
                ViewBag.IsNew = false;
                TreatmentModel treatmentModel = new TreatmentModel(t.Type, t.Description, t.Location, t.Particularities) { PatientEmail = t.Patient.Email, TreatmentId = t.Id };
                return View(treatmentModel);
            } else
            {
                ViewBag.IsNew = true;
                return View(new TreatmentModel() { PatientEmail = p});
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddTreatment(TreatmentModel model)
        {
            if (ModelState.IsValid)
            {
                if(model.TreatmentId != 0)
                {
                    IdentityUser usr = userManager.GetUserAsync(HttpContext.User).Result;
                    string email = usr.Email;
                    Domain.Treator treator = treatorRepository.GetTreatorByEmail(email);

                    Domain.Patient p = patientRepository.GetPatientByEmail(model.PatientEmail);

                    Treatment t = new Treatment(model.Type, model.Description, model.Location, model.Particularities, treator, p, DateTime.Now);
                    addTreatmentService.UpdateTreatment(t, model.TreatmentId, Response.HttpContext.Request.Cookies["apiToken"]);
                    PatientFile pf = patientFileRepository.GetCurrentPatientFileForPatient(p);
                    return RedirectToAction("Index", "PatientFile", pf);
                } else
                {
                    IdentityUser usr = userManager.GetUserAsync(HttpContext.User).Result;
                    string email = usr.Email;
                    Domain.Treator treator = treatorRepository.GetTreatorByEmail(email);

                    Domain.Patient p = patientRepository.GetPatientByEmail(model.PatientEmail);

                    Treatment t = new Treatment(model.Type, model.Description, model.Location, model.Particularities, treator, p, DateTime.Now);

                    if (addTreatmentService.AddTreatment(t, Response.HttpContext.Request.Cookies["apiToken"]))
                    {
                        PatientFile pf = patientFileRepository.GetCurrentPatientFileForPatient(p);
                        pf.Treatments.Add(t);
                        patientFileRepository.UpdatePatientFile(pf);
                        return RedirectToAction("Index", "PatientFile", pf);
                    } else
                    {
                        return View("Error");
                    }

                }
            } else
            {
                ViewBag.IsNew = true;
                ViewBag.TreatmentTypes = GetTreatmentTypes();
                return View(model);
            }
        }

        public ActionResult DeleteTreatment(int treatmentId)
        {
            if(treatmentId != 0)
            {
                Treatment t = treatmentRepository.GetTreatmentById(treatmentId);

                Domain.Patient p = patientRepository.GetPatientByEmail(t.Patient.Email);
                PatientFile pf = patientFileRepository.GetCurrentPatientFileForPatient(p);
                
                treatmentRepository.DeleteTreatment(t);

                return RedirectToAction("Index", "PatientFile", pf);
            } else
            {
                ViewBag.IsNew = false;
                return View("Error");
            }
        }

        public IEnumerable<SelectListItem> GetTreatmentTypes()
        {
            
            return treatmentTypeRepository.GetAllTreatments(Response.HttpContext.Request.Cookies["apiToken"]).Select(t => new SelectListItem() { Text = t.Description, Value = t.Value});
        }

        public JsonResult IsDescriptionNecessaryForTreatment(string id)
        {
            return Json(treatmentTypeRepository.GetTreatmentById(id, Response.HttpContext.Request.Cookies["apiToken"]).RequireExplanation);
        }

        public IActionResult ToPatientList()
        {
            return RedirectToAction("Index", "Patient");
        }
    }
}

Fysio/Areas/Treator/Views/PatientFile/AddComment.cshtml
@model Fysio.Areas.Treator.Models.CommentModel

<script src="~/js/MenuItems.js"></script>
<link rel="stylesheet" href="~/css/Patient/AddPatientStyle.css" />

<body>

    <div class="form-add-patient">
        <div class="title">
            <h2>Opmerking toevoegen</h2>
        </div>
        <form asp-action="AddComment" method="post" class="form">
            <input asp-for="PatientFileId" value="@Model.PatientFileId" class="hidden" />
            <div class="form-personal">
                <div class="form-input-group">
                    <label asp-for="Description">Opmerking</label>
                    <textarea asp-for="Description" class="input-field-form" ></textarea>
                </div>

                <div class="form-input-group">
                    <label class="form-input-label" asp-for="VisibleForPatient">Zichtbaar voor</label>
                    <select asp-for="VisibleForPatient" class="input-field-form">
                        <option value="">Kies er een...</option>
                        <option value="true">Iedereen</option>
                        <option value="false">Alleen collega's</option>
                    </select>
                </div>
            </div>
            <div class="form-submit">
                <button class="btn-active-menu" type="submit">Voeg opmerking toe</button>
                <div asp-validation-summary="All"></div>
            </div>
        </form>
    </div>
</body>

<script>
    activeMenu2();
</script>

Fysio/Areas/Treator/Views/PatientFile/Index.cshtml
@model Domain.PatientFile

<link rel="stylesheet" href="~/css/PatientFile/PatientFileStyle.css"/>

<script src="~/js/MenuItems.js"></script>

<body class="patientfile-body">
    <div class="patientfile">
        <div class="patient-link">
            <div class="patient-link-title">
                <h4>Patient</h4>
            </div>
            <div class="patient-link-information">
                <div class="patient-link-information-head">
                    <span>Naam:</span>
                    <br />
                    <span>Leeftijd:</span>
                </div>
                <div class="patient-link-information-content">
                    <span>@Model.Patient.Name</span>
                    <br />
                    <span>@Model.Age</span>
                </div>
            </div>
            <div class="patient-link-icon">
                <a asp-action="PatientDetail" asp-area="Treator" asp-controller="Patient" asp-route-id="@Model.Patient.Id">
                    <img src="~/icons/chevron-right.svg" alt="arrow to the right" />
                </a>
            </div>
        </div>
        <div class="treatmentplan">
            <div class="treatmentplan-title">
                <h4>Behandelplan</h4>
            </div>
            <div class="treatmentplan-info">
                <div class="treatmentplan-info-head">
                    <span>Behandelingen p/w:</span>
                    <br />
                    <span>Minuten per sessie:</span>
                </div>
                <div class="treatmentplan-info-content">
                    <span>
                        @Model.TreatmentPlan.TreatmentsPerWeek
                    </span>
                    <br />
                    <span>
                        @Model.TreatmentPlan.MinutesPerSession
                    </span>
                </div>
            </div>
            <div class="treatmentplan-diagnosis">
                <div class="treatmentplan-diagnosis-head">
                    <span>Diagnose code:</span>
                    <br />
                    <span>Diagnose omschrijving:</span>
                </div>
                <div class="treatmentplan-diagnosis-content">
                    <span>
                        @Model.DiagnosisCode
                    </span>
                    <br />
                    <span>
                        @Model.DiagnosisDescription
                    </span>
                </div>
            </div>
        </div>
        <div class="intake">
            <div class="intake-title">
                <h4>Intake</h4>
            </div>
            <div class="intake-info">
                <div class="intake-info-dates">
                    <div class="intake-info-dates-head">
                        <span>Startdatum:</span>
                        <br />
                        <span>Einddatum:</span>
                    </div>
                    <div class="intake-info-dates-content">
                        <span>@Model.StartDate.ToShortDateString()</span>
                        <br />
                        @if (Model.EndDate == DateTime.MinValue)
                        {
                            <span>Nog in traject</span>
                        }
                        else
                        {
                            <span>@Model.EndDate.ToShortDateString()</span>
                        }

                    </div>
                </div>
                <div class="intake-info-treators">
                    <div class="intake-info-treators-head">
                        <span>Intaker:</span>
                        <br />
                        @if (Model.SupervisingTreator != null)
                        {
                            <span>Supervisor:</span>
                            <br/>
                        }
                        <span>Hoofdbehandelaar:</span>
                    </div>
                    <div class="intake-info-treators-content">
                        <span>@Model.Intaker.Name</span>
                        <br />
                        @if (Model.SupervisingTreator != null)
                        {
                            <span>@Model.SupervisingTreator.Name</span>
                            <br/>
                        }
                        <span>@Model.MainTreator.Name</span>
                    </div>
                </div>
                <div class="intake-info-complaints">
                    <div class="intake-info-complaints-head">
                        <span>Klachten:</span>
                    </div>
                    <div class="intake-info-complaints-content">
                        <span>@Model.Complaints</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="comments">
            <div class="comments-title">
                <h4>Opmerkingen</h4>
            </div>
            <div class="comments-list">
                @if (Model.Comments.Count > 0)
                {
                    @foreach (Domain.Comment comment in Model.Comments.OrderBy(p => p.CreationDateTime))
                    {
                        <div class="comments-list-item">
                            <div class="comments-list-item-title">
                                <h6>@comment.CreationDateTime.ToShortDateString()</h6>
                            </div>
                            <div class="comments-list-item-info">
                                <div class="comments-list-item-info-head">
                                    <span>Maker:</span>
                                    <br />
                                    <span>Zichtbaarheid:</span>
                                    <br />
                                    <span class="comment">Opmerking:</span>
                                </div>
                                <div class="comments-list-item-info-content">
                                    <span>@comment.Creator.Name</span>
                                    <br />
                                    @if (comment.VisibleForPatient)
                                    {
                                        <span>Iedereen</span>
                                    }
                                    else
                                    {
                                        <span>Alleen collega's</span>
                                    }
                                    <br />
                                    <span>@comment.Description</span>
                                </div>
                            </div>

                        </div>
                    }
                }
                else
                {
                    <h6>Er zijn geen comments</h6>
                }
            </div>
            <div class="comments-btn">
                <a asp-action="AddComment" asp-area="Treator" asp-controller="PatientFile" asp-route-id="@Model.Id" class="link-styled">Opmerking maken</a>
            </div>
        </div>
        <div class="treatments">
            <div class="treatments-title">
                <h4>Behandelingen</h4>
            </div>
            <div class="treatments-list">
                @if (Model.Treatments.Count > 0)
                {
                    @foreach (Domain.Treatment treatment in Model.Treatments.OrderByDescending(p => p.TreatmentDateTime))
                    {
                        <div class="treatments-list-item">
                            <a asp-action="Index" asp-area="Treator" asp-controller="Treatment" asp-route-id="@treatment.Id">
                                <div class="treatments-list-item-title">
                                    <h6>@treatment.TreatmentDateTime.ToShortDateString()</h6>
                                </div>
                                <div class="treatments-list-item-info">
                                    <div class="treatments-list-item-info-head">
                                        <span>Type:</span>
                                        <br />
                                        <span>Behandelaar:</span>
                                    </div>
                                    <div class="treatments-list-item-info-content">
                                        <span>@treatment.Type</span>
                                        <br />
                                        <span>@treatment.Treator.Name</span>
                                    </div>
                                </div>
                            </a>
                        </div>
                    }
                    }
                    else
                    {
                        <h6>Er zijn nog geen behandelingen</h6>
                    }
            </div>
            <div class="treatments-btn">
                
                    <a class="link-styled" asp-action="AddTreatment" asp-area="Treator" asp-controller="Treatment" asp-route-p="@Model.Patient.Email" asp-route-id="0">Behandeling maken</a>
                </div>
        </div>
    </div>
</body>


<script>
    activeMenu2();
</script>